import type { RawEcotoxRecord } from './types';

export const SSD_FIXTURE_ROWS: RawEcotoxRecord[] = [
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Daphnia magna',
    conc1_mean: 0.006,
    species_group: 'Crustacean',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-001',
    test_id: 'fixture-test-001',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Daphnia magna',
    conc1_mean: 0.009,
    species_group: 'Crustacean',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-002',
    test_id: 'fixture-test-002',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Ceriodaphnia dubia',
    conc1_mean: 0.011,
    species_group: 'Aquatic Invertebrates',
    media_type: 'FW',
    endpoint: 'Reproduction',
    reference_number: 'fixture-ref-003',
    test_id: 'fixture-test-003',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Pimephales promelas',
    conc1_mean: 0.018,
    species_group: 'Fish',
    media_type: 'FW',
    endpoint: 'Growth',
    reference_number: 'fixture-ref-004',
    test_id: 'fixture-test-004',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Oncorhynchus mykiss',
    conc1_mean: 0.022,
    species_group: 'Fish',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-005',
    test_id: 'fixture-test-005',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Lemna minor',
    conc1_mean: 0.03,
    species_group: 'Aquatic Plants',
    media_type: 'FW',
    endpoint: 'Growth',
    reference_number: 'fixture-ref-006',
    test_id: 'fixture-test-006',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Pseudokirchneriella subcapitata',
    conc1_mean: 0.037,
    species_group: 'Algae',
    media_type: 'FW',
    endpoint: 'Growth',
    reference_number: 'fixture-ref-007',
    test_id: 'fixture-test-007',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Hyalella azteca',
    conc1_mean: 0.045,
    species_group: 'Invertebrate',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-008',
    test_id: 'fixture-test-008',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Chironomus dilutus',
    conc1_mean: 0.052,
    species_group: 'Insects',
    media_type: 'FW',
    endpoint: 'Growth',
    reference_number: 'fixture-ref-009',
    test_id: 'fixture-test-009',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Xenopus laevis',
    conc1_mean: 0.07,
    species_group: 'Amphibian',
    media_type: 'FW',
    endpoint: 'Development',
    reference_number: 'fixture-ref-010',
    test_id: 'fixture-test-010',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Salvelinus fontinalis',
    conc1_mean: 0.085,
    species_group: 'Fish',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-015',
    test_id: 'fixture-test-015',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Americamysis bahia',
    conc1_mean: 0.019,
    species_group: 'Crustacean',
    media_type: 'MW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-011',
    test_id: 'fixture-test-011',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Cyprinodon variegatus',
    conc1_mean: 0.033,
    species_group: 'Fish',
    media_type: 'MW',
    endpoint: 'Growth',
    reference_number: 'fixture-ref-012',
    test_id: 'fixture-test-012',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Invalid endpoint species',
    conc1_mean: 'NR',
    species_group: 'Fish',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-013',
    test_id: 'fixture-test-013',
  },
  {
    chemical_name: 'Copper',
    species_scientific_name: 'Nonpositive species',
    conc1_mean: 0,
    species_group: 'Fish',
    media_type: 'FW',
    endpoint: 'Mortality',
    reference_number: 'fixture-ref-014',
    test_id: 'fixture-test-014',
  },
];
