import { describe, expect, it, vi } from 'vitest';
import { getPaperAdminAccess, getTrustedPaperReviewIdentity, isPaperAdminRole, validateTrustedReviewFilters } from '../paper-admin-guard';
function client(user: { id: string } | null, roles: unknown[] = [], error?: unknown) { const query: any = { select: vi.fn(() => query), eq: vi.fn(() => query), in: vi.fn(async () => ({ data: roles, error })) }; return { auth: { getUser: vi.fn(async () => ({ data: { user } })) }, from: vi.fn(() => query) } as any; }
describe('paper admin guard', () => {
  it.each(['admin', 'matrix_admin'])('allows %s', async (role) => { await expect(getPaperAdminAccess(client({ id: 'u1' }, [{ role }]))).resolves.toMatchObject({ allowed: true, role }); });
  it('rejects unauthenticated, forbidden, and role-query errors', async () => { await expect(getPaperAdminAccess(client(null))).resolves.toMatchObject({ status: 401 }); await expect(getPaperAdminAccess(client({ id: 'u1' }, [{ role: 'reviewer' }]))).resolves.toMatchObject({ status: 403 }); await expect(getPaperAdminAccess(client({ id: 'u1' }, [], new Error('RLS')))).resolves.toMatchObject({ status: 403 }); });
  it('recognizes only explicit admin roles', () => { expect(isPaperAdminRole('admin')).toBe(true); expect(isPaperAdminRole('matrix_admin')).toBe(true); expect(isPaperAdminRole('owner')).toBe(false); });
  it('constructs trusted release-manifest identity from authenticated paper, guide, and cohort authorities', async () => { const identity = await getTrustedPaperReviewIdentity(); expect(identity.manifestSha256).not.toBe('feb62bd63c46f9b799a705da9ccb6db41974512ca4c73d9582111eeb3ae47337'); expect(identity.manifestSha256).toMatch(/^[a-f0-9]{64}$/); expect(identity.releaseIdentity).toContain('1.0.11-remediated-7-8-successor-20260918-D'); expect(identity.cohortQuestionIds.size).toBeGreaterThan(0); });
  it('fails incompatible document, manifest, unknown identities, and cross-membership closed', async () => { const identity = await getTrustedPaperReviewIdentity(); expect(validateTrustedReviewFilters({ documentVersion: 'wrong' }, identity)).toBe(false); expect(validateTrustedReviewFilters({ manifestSha256: 'b'.repeat(64) }, identity)).toBe(false); expect(validateTrustedReviewFilters({ cohortId: 'missing' }, identity)).toBe(false); const entries = [...identity.cohortQuestionIds.entries()]; const first = entries[0]; const other = entries.find((entry) => entry[0] !== first[0] && [...entry[1]].some((question) => !first[1].has(question))); if (other) { const question = [...other[1]].find((value) => !first[1].has(value))!; expect(validateTrustedReviewFilters({ cohortId: first[0], questionId: question }, identity)).toBe(false); } });
});
