// In-memory + on-disk audit log for the Agentic OS launch route.
//
// Step 6a shipped the in-memory ring buffer only. Step 6b adds a best-effort
// append-only file writer at `<cwd>/logs/agentic-os-launches.log` so the
// audit trail survives a dev-server restart and can be inspected with
// ordinary shell tools.
//
// File write is BEST-EFFORT: if the write fails (disk full, permission
// denied, EROFS on a CI image, etc.) we emit one console.warn and continue.
// The launch route is NOT made dependent on the audit file landing; the
// in-memory copy is always authoritative for the running process and the
// pid/runId have already been captured before the audit append is reached.
//
// File format: one JSON object per line. New entries are appended; the file
// is never rewritten. The directory is created lazily on first write.
//
// Lives outside route.ts because Next.js App Router constrains `route.ts`
// files to export only HTTP-verb handlers + a small allowlist of config
// exports; any other export triggers a type error at build time.

import fs from 'fs';
import path from 'path';

export interface AuditEntry {
  /** ISO 8601 timestamp of the spawn. */
  ts: string;
  /** Authenticated admin user's email; may be undefined if Supabase returns no email. */
  user_email: string | undefined;
  /** Child process PID; may be undefined if spawn returned without a pid. */
  pid: number | undefined;
  /** UUID generated by the route, primary handle for SSE attach. Step 6b+. */
  run_id?: string;
  /** Validated executable name (always a hardcoded literal from launch-validator). */
  exe: string;
  /** Validated argument vector (always derived from a hardcoded template). */
  args: readonly string[];
  /** Validated working directory (path.join(PROJECTS_ROOT, allowlisted-project)). */
  cwd: string;
  /** Project name from LaunchRequest (allowlisted). Step 6b+. */
  project?: string;
  /** Action key from LaunchRequest (allowlisted). Step 6b+. */
  action?: string;
}

// Cap to prevent unbounded memory growth on a long-running dev server. 500
// entries at ~250 bytes each is ~125 KB; well under any realistic budget.
const AUDIT_LOG_CAP = 500;

// Relative to the Next.js process cwd (which is the SSTAC-Dashboard repo root
// in normal `npm run dev` invocations). Path.join guarantees correct
// separators on Windows.
const AUDIT_LOG_DIR = path.join(process.cwd(), 'logs');
const AUDIT_LOG_FILE = path.join(AUDIT_LOG_DIR, 'agentic-os-launches.log');

// Cached directory-ensured flag so we don't hit the FS for every entry.
let dirEnsured = false;

const launchAuditLog: AuditEntry[] = [];

function ensureLogDir(): boolean {
  if (dirEnsured) return true;
  try {
    fs.mkdirSync(AUDIT_LOG_DIR, { recursive: true });
    dirEnsured = true;
    return true;
  } catch (err) {
    // Permission denied / EROFS / etc -- continue without persistence.
    console.warn(
      '[agentic-os audit] failed to create logs/ directory; persistence disabled:',
      err instanceof Error ? err.message : String(err),
    );
    return false;
  }
}

function appendToFile(entry: AuditEntry): void {
  if (!ensureLogDir()) return;
  try {
    const line = JSON.stringify(entry) + '\n';
    // appendFileSync is fine here: launch route latency is dominated by spawn,
    // and a write of ~250 bytes is sub-millisecond on any local disk.
    fs.appendFileSync(AUDIT_LOG_FILE, line, { encoding: 'utf-8' });
  } catch (err) {
    console.warn(
      '[agentic-os audit] append to logs/agentic-os-launches.log failed:',
      err instanceof Error ? err.message : String(err),
    );
    // Disable further attempts this session? No -- the failure may be
    // transient (e.g. disk briefly full). Per-call retry is the simpler
    // correctness story.
  }
}

export function appendLaunchAudit(entry: AuditEntry): void {
  launchAuditLog.push(entry);
  if (launchAuditLog.length > AUDIT_LOG_CAP) {
    launchAuditLog.splice(0, launchAuditLog.length - AUDIT_LOG_CAP);
  }
  appendToFile(entry);
}

/**
 * Snapshot accessor. Returns a defensive copy; mutations to the returned
 * array do not affect the underlying store.
 */
export function getLaunchAuditLog(): readonly AuditEntry[] {
  return launchAuditLog.slice();
}

/**
 * Test-only reset. Lets unit + integration tests start from a clean log
 * without leaking state between cases.
 */
export function __resetLaunchAuditLogForTest(): void {
  launchAuditLog.length = 0;
  dirEnsured = false;
}

export const __AUDIT_LOG_CAP_FOR_TEST = AUDIT_LOG_CAP;
export const __AUDIT_LOG_FILE_FOR_TEST = AUDIT_LOG_FILE;
