// Agentic OS stream route -- GET /api/agentic-os/stream/[runId] (step 6b).
//
// Server-Sent Events endpoint that mirrors the child process's stdout/stderr
// back to the admin page's TerminalPanel logs tab. The handle is the runId
// (uuid) generated by the launch route, NOT the pid -- pids are reused by
// the OS as soon as a process exits and would collide.
//
// Wire protocol (mirrors engine-v2 /chat sseEvent helper):
//   On connect:
//     - stdout / stderr buffered lines (one event each) so the client
//       reconstructs the output that arrived before subscription
//     - 'snapshot_complete' event marking the boundary between replay and live
//   While running:
//     - 'stdout' / 'stderr' events with { text, ts } payload, one per line
//     - heartbeat comment line ":" every 15s (proxy keepalive)
//   On child close:
//     - 'exit' event with { exitCode, exitedAt }
//     - controller.close(); the client's EventSource will see readyState === 2
//
// Gate sequence: the launch route's six gates are reused here for parity,
// minus the body-shape gate (this is a GET with no body) and minus the
// allowlist gate (the runId is the allowlist -- if it exists in the
// registry it was created by a request that already passed all six gates).
//
//   GATE 1: feature flag (env-launch-enabled)        -> 403
//   GATE 2: localhost origin                          -> 403
//   GATE 3: admin role (Supabase)                     -> 401/403
//   GATE 4: runId exists in registry                  -> 404
//
// CSRF is intentionally NOT applied: it's a same-origin GET (the launch route's
// localhost+admin gates already lock down access), and CSRF protection
// targets state-mutating verbs. EventSource cannot set custom headers anyway,
// so a Content-Type-based check would be impossible.

import { NextResponse, type NextRequest } from 'next/server';
import { requireAdminForApi } from '@/lib/engine-v2/admin_guards';
import { isAgenticOsLaunchEnabled } from '@/lib/agentic-os/feature-flag';
import { getRun, subscribe, type LogLine } from '@/lib/agentic-os/launch-runs';

export const runtime = 'nodejs';
// SSE streams must not be cached or buffered by Next.js or any upstream proxy.
// dynamic = 'force-dynamic' disables route-level caching even when the file
// would otherwise be classified as a static GET.
export const dynamic = 'force-dynamic';

const HEARTBEAT_INTERVAL_MS = 15_000;

function isLocalhostOrigin(origin: string): boolean {
  if (!origin) return false;
  try {
    const u = new URL(origin);
    return (
      u.hostname === 'localhost' ||
      u.hostname === '127.0.0.1' ||
      u.hostname === '[::1]' ||
      u.hostname === '::1'
    );
  } catch {
    return false;
  }
}

function sseEvent(event: string, data: Record<string, unknown>): string {
  return `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
}

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ runId: string }> },
): Promise<Response> {
  // GATE 1: feature flag.
  if (!isAgenticOsLaunchEnabled()) {
    return NextResponse.json(
      { error: 'launch_disabled_in_non_dev' },
      { status: 403 },
    );
  }

  // GATE 2: localhost. Prefer Origin; fall back to Referer (full URL).
  const originHeader = request.headers.get('origin');
  const refererHeader = request.headers.get('referer');
  let candidate = '';
  if (originHeader) {
    candidate = originHeader;
  } else if (refererHeader) {
    try {
      candidate = new URL(refererHeader).origin;
    } catch {
      candidate = '';
    }
  }
  // EventSource on some browsers omits the Origin header on same-origin GETs.
  // Fall back to request.nextUrl.origin in that case so a legitimate
  // same-origin subscription still passes the gate.
  if (!candidate) {
    candidate = request.nextUrl.origin;
  }
  if (!isLocalhostOrigin(candidate)) {
    return NextResponse.json({ error: 'localhost_only' }, { status: 403 });
  }

  // GATE 3: admin role.
  const auth = await requireAdminForApi();
  if (auth instanceof NextResponse) {
    return auth;
  }

  // GATE 4: runId exists in registry.
  const { runId } = await context.params;
  const state = getRun(runId);
  if (!state) {
    return NextResponse.json({ error: 'run_not_found' }, { status: 404 });
  }

  const encoder = new TextEncoder();
  const upstreamSignal = request.signal;

  // Cleanup state is lifted out of start() so the stream's cancel() callback
  // (fired when the consumer aborts WITHOUT request.signal firing -- rare but
  // possible when the runtime tears down the response) can drive the same
  // teardown path. Without this, the heartbeat timer would leak and the
  // subscription would stay attached.
  let closed = false;
  let heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  let unsubscribe: (() => void) | null = null;
  let controllerRef: ReadableStreamDefaultController<Uint8Array> | null = null;

  const cleanupAll = (): void => {
    if (closed) return;
    closed = true;
    if (heartbeatTimer) {
      clearInterval(heartbeatTimer);
      heartbeatTimer = null;
    }
    if (unsubscribe) {
      try { unsubscribe(); } catch { /* ignore */ }
      unsubscribe = null;
    }
    if (controllerRef) {
      try { controllerRef.close(); } catch { /* already closed */ }
      controllerRef = null;
    }
  };

  const stream = new ReadableStream<Uint8Array>({
    start(controller) {
      controllerRef = controller;

      const safeEnqueue = (chunk: string): void => {
        if (closed) return;
        try {
          controller.enqueue(encoder.encode(chunk));
        } catch {
          // Controller already errored / closed; nothing actionable.
        }
      };

      // Wire client-disconnect FIRST so an early abort during snapshot replay
      // still tears down cleanly. We do NOT kill the child here -- the child
      // outlives the SSE subscription and stays in the registry for later
      // subscribers / `listRuns()` inspection.
      if (upstreamSignal.aborted) {
        cleanupAll();
        return;
      }
      upstreamSignal.addEventListener('abort', cleanupAll, { once: true });

      // Replay the buffered stdout, then stderr, before subscribing. Order
      // within each stream is preserved; we do NOT attempt to interleave
      // stdout and stderr by timestamp because the client renders them in
      // separately-tagged log lines and the buffer is already chronological
      // per stream.
      for (const line of state.stdoutBuffer) {
        safeEnqueue(
          sseEvent('stdout', { text: line.text, ts: line.ts }),
        );
      }
      for (const line of state.stderrBuffer) {
        safeEnqueue(
          sseEvent('stderr', { text: line.text, ts: line.ts }),
        );
      }
      if (state.truncated) {
        safeEnqueue(
          sseEvent('truncated', {
            note: 'earlier output truncated (buffer cap)',
          }),
        );
      }
      safeEnqueue(sseEvent('snapshot_complete', { runId: state.runId }));

      // Subscribe BEFORE checking already-exited so we don't miss a race
      // where the child closed between the buffer replay above and the
      // subscribe call. subscribe() also handles the
      // already-exited-at-subscribe case by firing onExit on a microtask.
      unsubscribe = subscribe(
        state.runId,
        (line: LogLine) => {
          safeEnqueue(
            sseEvent(line.stream, { text: line.text, ts: line.ts }),
          );
        },
        (info) => {
          safeEnqueue(
            sseEvent('exit', {
              exitCode: info.exitCode,
              exitedAt: info.exitedAt,
            }),
          );
          cleanupAll();
        },
      );

      // Heartbeat. SSE comment lines (starting with ':') are ignored by
      // EventSource but keep idle connections alive through proxies.
      heartbeatTimer = setInterval(() => {
        safeEnqueue(`: heartbeat ${Date.now()}\n\n`);
      }, HEARTBEAT_INTERVAL_MS);
    },
    cancel() {
      // ReadableStream cancel fires when the consumer tears the stream down
      // (e.g. the runtime closing the response without surfacing an abort
      // signal). Drive the same cleanup path so the heartbeat timer + the
      // run-registry subscription don't leak.
      cleanupAll();
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      // Disable Next.js's automatic gzip on streamed responses -- compression
      // breaks SSE flushing because the buffer never fills.
      'X-Accel-Buffering': 'no',
    },
  });
}
