import { loadRevisedPaper, REVISED_PAPER_RELEASE_IDENTITY, REVISED_PAPER_SHA256, REVISED_PAPER_VERSION } from './revised-paper';
import { authenticateReviewerGuideAgainstPaper, getReviewerGuideContract } from './reviewer-guide';
import { getCohortManifest } from './cohort-contract';
import { sha256Object } from './paper/contracts';

export const PAPER_ADMIN_ROLES = ['admin', 'matrix_admin'] as const;
export type PaperAdminRole = (typeof PAPER_ADMIN_ROLES)[number];
export type PaperAdminUser = { id: string };
export type PaperAdminAccess = { allowed: true; user: PaperAdminUser; role: PaperAdminRole } | { allowed: false; status: 401 | 403; reason: 'unauthenticated' | 'forbidden' };
export type TrustedPaperReviewIdentity = { readonly documentVersion: typeof REVISED_PAPER_VERSION; readonly manifestSha256: string; readonly releaseIdentity: typeof REVISED_PAPER_RELEASE_IDENTITY; readonly cohortIds: ReadonlySet<string>; readonly questionIds: ReadonlySet<string>; readonly cohortQuestionIds: ReadonlyMap<string, ReadonlySet<string>> };
export type ReviewIdentityFilters = { documentVersion?: string; manifestSha256?: string; cohortId?: string; questionId?: string };
type SupabaseLike = { auth: { getUser: () => Promise<{ data?: { user?: PaperAdminUser | null }; error?: unknown }> }; from: (table: string) => any };
export function isPaperAdminRole(role: unknown): role is PaperAdminRole { return role === 'admin' || role === 'matrix_admin'; }
export async function getPaperAdminAccess(client: SupabaseLike): Promise<PaperAdminAccess> { let authResult: Awaited<ReturnType<SupabaseLike['auth']['getUser']>>; try { authResult = await client.auth.getUser(); } catch { return { allowed: false, status: 401, reason: 'unauthenticated' }; } const user = authResult.data?.user; if (authResult.error || !user?.id) return { allowed: false, status: 401, reason: 'unauthenticated' }; let roleResult: { data?: Array<{ role?: unknown }>; error?: unknown }; try { roleResult = await client.from('user_roles').select('role').eq('user_id', user.id).in('role', PAPER_ADMIN_ROLES); } catch { return { allowed: false, status: 403, reason: 'forbidden' }; } if (roleResult.error) return { allowed: false, status: 403, reason: 'forbidden' }; const role = roleResult.data?.map((row) => row.role).find(isPaperAdminRole); return role ? { allowed: true, user, role } : { allowed: false, status: 403, reason: 'forbidden' }; }
export async function getTrustedPaperReviewIdentity(): Promise<TrustedPaperReviewIdentity> { const paper = loadRevisedPaper(REVISED_PAPER_VERSION); if (paper.documentVersion !== REVISED_PAPER_VERSION || paper.sha256 !== REVISED_PAPER_SHA256 || paper.releaseIdentity !== REVISED_PAPER_RELEASE_IDENTITY) throw new Error('Trusted paper release identity mismatch'); const guide = getReviewerGuideContract(); await authenticateReviewerGuideAgainstPaper(guide, paper.content); const cohorts = getCohortManifest(); const questionByNumber = new Map(guide.questions.map((question) => [question.number, question.id])); const cohortQuestionIdsForManifest = Object.fromEntries(cohorts.cohorts.map((cohort) => [cohort.id, cohort.questionNumbers.map((number) => questionByNumber.get(number)).filter((id): id is string => Boolean(id))])); const manifestIdentity = { schemaVersion: 'matrix-paper-review-manifest-v1', documentVersion: paper.documentVersion, paperSha256: paper.sha256, reviewerGuideReleaseIdentity: guide.releaseIdentity, cohortsReleaseIdentity: cohorts.releaseIdentity, reviewerGuideSha256: sha256Object(guide), cohortsSha256: sha256Object(cohorts), questionIds: guide.questions.map((question) => question.id), cohortQuestionIds: cohortQuestionIdsForManifest } as const; const manifestSha256 = sha256Object(manifestIdentity); if (!manifestSha256 || manifestSha256 === paper.sha256) throw new Error('Trusted review manifest mismatch'); const questionIds = new Set(guide.questions.map((question) => question.id)); const cohortQuestionIds = new Map<string, ReadonlySet<string>>(); for (const cohort of cohorts.cohorts) { const members = new Set(cohort.questionNumbers.map((number) => questionByNumber.get(number)).filter((id): id is string => typeof id === 'string')); if (members.size !== cohort.questionNumbers.length) throw new Error('Trusted cohort question membership mismatch'); cohortQuestionIds.set(cohort.id, members); } const cohortIds = new Set(cohortQuestionIds.keys()); if (questionIds.size !== guide.questions.length || cohortIds.size !== cohorts.cohorts.length) throw new Error('Trusted contract contains duplicate identities'); return Object.freeze({ documentVersion: paper.documentVersion, manifestSha256, releaseIdentity: paper.releaseIdentity, cohortIds, questionIds, cohortQuestionIds }); }
export function validateTrustedReviewFilters(filters: ReviewIdentityFilters, trusted: TrustedPaperReviewIdentity): boolean { if (filters.documentVersion !== undefined && filters.documentVersion !== trusted.documentVersion) return false; if (filters.manifestSha256 !== undefined && filters.manifestSha256.toLowerCase() !== trusted.manifestSha256) return false; if (filters.cohortId !== undefined && !trusted.cohortIds.has(filters.cohortId)) return false; if (filters.questionId !== undefined && !trusted.questionIds.has(filters.questionId)) return false; if (filters.cohortId !== undefined && filters.questionId !== undefined && !trusted.cohortQuestionIds.get(filters.cohortId)?.has(filters.questionId)) return false; return true; }
