import { beforeEach, describe, expect, it, vi } from 'vitest';
import { REVIEW_RESPONSE_SELECT } from '@/lib/matrix-options/paper/review-csv';

const state = vi.hoisted(() => ({ access: { allowed: true, user: { id: 'admin-1' }, role: 'admin' } as any, rows: [] as unknown[], error: null as unknown }));
const builder = vi.hoisted(() => { const value: any = { select: vi.fn(), eq: vi.fn(), then: vi.fn() }; value.select.mockReturnValue(value); value.eq.mockReturnValue(value); value.then.mockImplementation((resolve: (result: unknown) => unknown) => resolve({ data: state.rows, error: state.error })); return value; });
vi.mock('next/headers', () => ({ cookies: vi.fn(async () => ({ get: vi.fn() })) }));
vi.mock('@supabase/ssr', () => ({ createServerClient: vi.fn(() => ({ from: vi.fn(() => builder) })) }));
vi.mock('@/lib/matrix-options/paper-admin-guard', async (importOriginal) => { const actual = await importOriginal<typeof import('@/lib/matrix-options/paper-admin-guard')>(); return { ...actual, getPaperAdminAccess: vi.fn(async () => state.access), getTrustedPaperReviewIdentity: vi.fn(async () => ({ documentVersion: 'v1', manifestSha256: 'a'.repeat(64), releaseIdentity: 'r', cohortIds: new Set(['c1']), questionIds: new Set(['q1']), cohortQuestionIds: new Map([['c1', new Set(['q1'])]]) })) }; });
import { GET } from '../route';

const valid = (extra: Record<string, unknown> = {}) => ({ id: 'r1', user_id: 'u1', document_version: 'v1', manifest_sha256: 'a'.repeat(64), cohort_id: 'c1', question_id: 'q1', draft_text: null, submitted_text: 'answer', revision: 1, submitted_revision: 1, submitted_at: '2026-09-17T00:00:00Z', updated_at: '2026-09-17T00:00:01Z', ...extra });
describe('paper review export route', () => { beforeEach(() => { state.access = { allowed: true, user: { id: 'admin-1' }, role: 'admin' }; state.rows = [valid()]; state.error = null; builder.select.mockClear(); builder.eq.mockClear(); });
  it.each(['admin', 'matrix_admin'])('exports authorized %s data, exact frozen columns, and derived status filter', async (role) => { state.access = { allowed: true, user: { id: 'admin-1' }, role }; const response = await GET(new Request('http://localhost?cohortId=c1&status=submitted')); expect(response.status).toBe(200); expect(await response.text()).toContain('submittedRevision'); expect(builder.select).toHaveBeenCalledWith(REVIEW_RESPONSE_SELECT); expect(builder.eq).toHaveBeenCalledWith('cohort_id', 'c1'); expect(builder.eq).not.toHaveBeenCalledWith('status', 'submitted'); });
  it('rejects unauthenticated and forbidden access', async () => { state.access = { allowed: false, status: 401, reason: 'unauthenticated' }; expect((await GET(new Request('http://localhost'))).status).toBe(401); state.access = { allowed: false, status: 403, reason: 'forbidden' }; expect((await GET(new Request('http://localhost'))).status).toBe(403); });
  it('resets state and covers empty, malformed, mixed, query failure, and incompatible manifest', async () => { state.rows = []; expect((await GET(new Request('http://localhost'))).status).toBe(200); state.rows = [valid({ revision: '1' })]; expect((await GET(new Request('http://localhost'))).status).toBe(500); state.rows = [valid(), valid({ question_id: 'q2' })]; expect((await GET(new Request('http://localhost'))).status).toBe(500); state.rows = [valid()]; state.error = new Error('database'); expect((await GET(new Request('http://localhost'))).status).toBe(500); state.error = null; expect((await GET(new Request(`http://localhost?manifestSha256=${'b'.repeat(64)}`))).status).toBe(409); });
});
