import { beforeEach, describe, expect, it, vi } from 'vitest';
import { REVIEW_RESPONSE_SELECT } from '@/lib/matrix-options/paper/review-csv';

const state = vi.hoisted(() => ({ access: { allowed: true, user: { id: 'admin-1' }, role: 'admin' } as any, rows: [] as unknown[], error: null as unknown }));
const builder = vi.hoisted(() => { const value: any = { select: vi.fn(), eq: vi.fn(), gt: vi.fn(), order: vi.fn(), limit: vi.fn(), then: vi.fn(), after: null as string | null, size: Infinity }; value.select.mockImplementation(() => { value.after = null; value.size = Infinity; return value; }); value.eq.mockReturnValue(value); value.order.mockReturnValue(value); value.gt.mockImplementation((_column: string, id: string) => { value.after = id; return value; }); value.limit.mockImplementation((size: number) => { value.size = size; return value; }); value.then.mockImplementation((resolve: (result: unknown) => unknown) => { const sorted = [...(state.rows as Array<{ id?: string }>)].sort((a, b) => String(a.id).localeCompare(String(b.id))); const after = value.after; return resolve({ data: state.error ? null : sorted.filter((row) => after === null || String(row.id) > after).slice(0, value.size), error: state.error }); }); return value; });
vi.mock('next/headers', () => ({ cookies: vi.fn(async () => ({ get: vi.fn() })) }));
vi.mock('@supabase/ssr', () => ({ createServerClient: vi.fn(() => ({ from: vi.fn(() => builder) })) }));
vi.mock('@/lib/matrix-options/paper-admin-guard', async (importOriginal) => { const actual = await importOriginal<typeof import('@/lib/matrix-options/paper-admin-guard')>(); return { ...actual, getPaperAdminAccess: vi.fn(async () => state.access), getTrustedPaperReviewIdentity: vi.fn(async () => ({ documentVersion: 'v1', manifestSha256: 'a'.repeat(64), releaseIdentity: 'r', cohortIds: new Set(['c1']), questionIds: new Set(['q1']), cohortQuestionIds: new Map([['c1', new Set(['q1'])]]) })) }; });
import { GET } from '../route';

const valid = (extra: Record<string, unknown> = {}) => ({ id: 'r1', user_id: 'u1', document_version: 'v1', manifest_sha256: 'a'.repeat(64), cohort_id: 'c1', question_id: 'q1', draft_text: null, submitted_text: 'answer', revision: 1, submitted_revision: 1, submitted_at: '2026-09-17T00:00:00Z', updated_at: '2026-09-17T00:00:01Z', ...extra });
describe('paper review export route', () => { beforeEach(() => { state.access = { allowed: true, user: { id: 'admin-1' }, role: 'admin' }; state.rows = [valid()]; state.error = null; builder.select.mockClear(); builder.eq.mockClear(); builder.gt.mockClear(); builder.limit.mockClear(); builder.order.mockClear(); });
  it.each(['admin', 'matrix_admin'])('exports authorized %s data, exact frozen columns, and derived status filter', async (role) => { state.access = { allowed: true, user: { id: 'admin-1' }, role }; const response = await GET(new Request('http://localhost?cohortId=c1&status=submitted')); expect(response.status).toBe(200); expect(await response.text()).toContain('submittedRevision'); expect(builder.select).toHaveBeenCalledWith(REVIEW_RESPONSE_SELECT); expect(builder.eq).toHaveBeenCalledWith('cohort_id', 'c1'); expect(builder.eq).not.toHaveBeenCalledWith('status', 'submitted'); });
  it('rejects unauthenticated and forbidden access', async () => { state.access = { allowed: false, status: 401, reason: 'unauthenticated' }; expect((await GET(new Request('http://localhost'))).status).toBe(401); state.access = { allowed: false, status: 403, reason: 'forbidden' }; expect((await GET(new Request('http://localhost'))).status).toBe(403); });
  it('resets state and covers empty, malformed, mixed, query failure, and incompatible manifest', async () => { state.rows = []; expect((await GET(new Request('http://localhost'))).status).toBe(200); state.rows = [valid({ revision: '1' })]; expect((await GET(new Request('http://localhost'))).status).toBe(500); state.rows = [valid(), valid({ question_id: 'q2' })]; expect((await GET(new Request('http://localhost'))).status).toBe(500); state.rows = [valid()]; state.error = new Error('database'); expect((await GET(new Request('http://localhost'))).status).toBe(500); state.error = null; expect((await GET(new Request(`http://localhost?manifestSha256=${'b'.repeat(64)}`))).status).toBe(409); });
  it('always scopes the database read to the trusted release, even with no filters (a second release cannot fail the export closed)', async () => { const response = await GET(new Request('http://localhost')); expect(response.status).toBe(200); expect(builder.eq).toHaveBeenCalledWith('document_version', 'v1'); expect(builder.eq).toHaveBeenCalledWith('manifest_sha256', 'a'.repeat(64)); });
  it('keyset-pages through every row past the PostgREST max-rows limit (no silent truncation, no offset drift)', async () => { state.rows = Array.from({ length: 1001 }, (_, index) => valid({ id: `r${index}`, user_id: `u${String(index).padStart(4, '0')}` })); const response = await GET(new Request('http://localhost')); expect(response.status).toBe(200); const lines = (await response.text()).trim().split(/\r?\n/); expect(lines).toHaveLength(1002); expect(builder.limit).toHaveBeenCalledWith(1000); expect(builder.order).toHaveBeenCalledWith('id', { ascending: true }); expect(builder.gt).toHaveBeenCalledTimes(2); });
  it('never sends the caller release filters as extra case-sensitive predicates (upper-case hash still returns rows)', async () => { const response = await GET(new Request(`http://localhost?manifestSha256=${'A'.repeat(64)}`)); expect(response.status).toBe(200); expect(builder.eq).not.toHaveBeenCalledWith('manifest_sha256', 'A'.repeat(64)); expect(await response.text()).toContain('answer'); });
  it('keyset paging never duplicates a row when a response is inserted between page requests', async () => { const base = Array.from({ length: 1000 }, (_, index) => valid({ id: `r${String(index).padStart(5, '0')}`, user_id: `u${index}` })); state.rows = base; let calls = 0; builder.limit.mockImplementation((size: number) => { builder.size = size; calls += 1; if (calls === 2) state.rows = [valid({ id: 'r00000a', user_id: 'late' }), ...base]; return builder; }); const response = await GET(new Request('http://localhost')); expect(response.status).toBe(200); const lines = (await response.text()).trim().split(/\r?\n/); const users = lines.slice(1).map((line) => line.split(',')[4]); expect(new Set(users).size).toBe(users.length); expect(users).toHaveLength(1000); });
});
