import { REVIEW_RESPONSE_TEXT_LIMIT, reviewResponseStatusLabel, type ReviewResponseRow } from './review-responses';
import type { TrustedPaperReviewIdentity } from '../paper-admin-guard';
export const REVIEW_RESPONSE_SELECT = 'id,user_id,document_version,manifest_sha256,cohort_id,question_id,draft_text,submitted_text,revision,submitted_revision,submitted_at,updated_at';
export const REVIEW_CSV_COLUMNS = ['documentVersion', 'manifestSha256', 'cohortId', 'questionId', 'userId', 'draftText', 'submittedText', 'currentRevision', 'submittedRevision', 'submittedAt', 'updatedAt', 'status'] as const;
export type ReviewRow = { documentVersion: string; manifestSha256: string; cohortId: string; questionId: string; userId: string; draftText: string | null; submittedText: string | null; currentRevision: number; submittedRevision: number | null; submittedAt: string | null; updatedAt: string | null; status: ReturnType<typeof reviewResponseStatusLabel> };
function nonBlank(value: unknown): string | null { if (typeof value !== 'string') return null; const result = value.trim(); return result || null; }
function hashText(value: unknown): string | null { const result = nonBlank(value); return result ? result.toLowerCase() : null; }
type Alias<T> = { ok: boolean; value: T | null };
function aliasMany<T>(value: Record<string, unknown>, keys: readonly string[], normalize: (input: unknown) => T | null, required = false): Alias<T> { const present = keys.filter((key) => Object.prototype.hasOwnProperty.call(value, key)); if (!present.length) return { ok: !required, value: null }; const values = present.map((key) => ({ raw: value[key], normalized: normalize(value[key]) })); if (values.some((item) => item.normalized === null && item.raw !== null && item.raw !== undefined)) return { ok: false, value: null }; const nonNull = values.map((item) => item.normalized).filter((item): item is T => item !== null); if (nonNull.some((item) => item !== nonNull[0])) return { ok: false, value: null }; return { ok: !required || nonNull.length > 0, value: nonNull[0] || null }; }
export function normalizeTimestamp(value: unknown): string | null { if (value === null || value === undefined || typeof value !== 'string') return null; const text = value.trim(); const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{3}))?Z$/.exec(text); if (!match) return null; const parsed = Date.parse(text); if (!Number.isFinite(parsed)) return null; const date = new Date(parsed); const millis = match[7] ? Number(match[7]) : 0; if (date.getUTCFullYear() !== Number(match[1]) || date.getUTCMonth() + 1 !== Number(match[2]) || date.getUTCDate() !== Number(match[3]) || date.getUTCHours() !== Number(match[4]) || date.getUTCMinutes() !== Number(match[5]) || date.getUTCSeconds() !== Number(match[6]) || date.getUTCMilliseconds() !== millis) return null; return date.toISOString(); }
function revision(value: unknown): number | null { if (value === null || value === undefined) return null; return typeof value === 'number' && Number.isFinite(value) && Number.isInteger(value) && value >= 0 ? value : null; }
function text(value: unknown): string | null { return typeof value === 'string' && value.length <= REVIEW_RESPONSE_TEXT_LIMIT ? value : null; }
function asRow(raw: unknown): ReviewRow | null { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null; const value = raw as Record<string, unknown>; const documentVersion = aliasMany(value, ['document_version', 'documentVersion'], nonBlank, true); const manifestSha256 = aliasMany(value, ['manifest_sha256', 'manifestSha256'], hashText, true); const cohortId = aliasMany(value, ['cohort_id', 'cohortId'], nonBlank, true); const questionId = aliasMany(value, ['question_id', 'questionId'], nonBlank, true); const userId = aliasMany(value, ['user_id', 'userId'], nonBlank, true); const draftText = aliasMany(value, ['draft_text', 'draftText'], text); const submittedText = aliasMany(value, ['submitted_text', 'submittedText'], text); const currentRevision = aliasMany(value, ['revision', 'current_revision', 'currentRevision'], revision, true); const submittedRevision = aliasMany(value, ['submitted_revision', 'submittedRevision'], revision); const submittedTimestamp = aliasMany(value, ['submitted_at', 'submittedAt'], normalizeTimestamp); const updatedTimestamp = aliasMany(value, ['updated_at', 'updatedAt'], normalizeTimestamp); const suppliedStatus = aliasMany(value, ['status', 'review_status', 'reviewStatus'], nonBlank); if (!documentVersion.ok || !manifestSha256.ok || !cohortId.ok || !questionId.ok || !userId.ok || !draftText.ok || !submittedText.ok || !currentRevision.ok || !submittedRevision.ok || !submittedTimestamp.ok || !updatedTimestamp.ok || !suppliedStatus.ok || !/^[0-9a-f]{64}$/.test(manifestSha256.value || '')) return null; const current = currentRevision.value!; const submittedRev = submittedRevision.value; const status = reviewResponseStatusLabel({ draft_text: draftText.value, submitted_text: submittedText.value, revision: current, submitted_revision: submittedRev } as ReviewResponseRow); if (suppliedStatus.value !== null && suppliedStatus.value !== status) return null; return { documentVersion: documentVersion.value!, manifestSha256: manifestSha256.value!, cohortId: cohortId.value!, questionId: questionId.value!, userId: userId.value!, draftText: draftText.value, submittedText: submittedText.value, currentRevision: current, submittedRevision: submittedRev, submittedAt: submittedTimestamp.value, updatedAt: updatedTimestamp.value, status }; }
export function normalizeReviewRows(rawRows: unknown, trusted: TrustedPaperReviewIdentity): ReviewRow[] | null { if (!trusted || !Array.isArray(rawRows)) return null; const rows = rawRows.map(asRow); if (rows.some((row) => row === null)) return null; const normalized = rows as ReviewRow[]; if (normalized.some((row) => row.documentVersion !== trusted.documentVersion || row.manifestSha256 !== trusted.manifestSha256 || !trusted.cohortQuestionIds.get(row.cohortId)?.has(row.questionId))) return null; return normalized; }
function codeUnitCompare(a: string, b: string): number { const length = Math.min(a.length, b.length); for (let index = 0; index < length; index += 1) { const left = a.charCodeAt(index); const right = b.charCodeAt(index); if (left !== right) return left < right ? -1 : 1; } return a.length === b.length ? 0 : a.length < b.length ? -1 : 1; }
function nullableCompare(a: string | null, b: string | null): number { return a === b ? 0 : a === null ? -1 : b === null ? 1 : codeUnitCompare(a, b); }
function rowCompare(a: ReviewRow, b: ReviewRow): number { for (const key of ['documentVersion', 'manifestSha256', 'cohortId', 'questionId', 'userId', 'status'] as const) { const result = codeUnitCompare(a[key], b[key]); if (result) return result; } const revisionResult = a.currentRevision - b.currentRevision || (a.submittedRevision ?? -1) - (b.submittedRevision ?? -1); return revisionResult || nullableCompare(a.submittedAt, b.submittedAt) || nullableCompare(a.updatedAt, b.updatedAt); }
function csvCell(value: string | number | null): string { const textValue = value === null ? '' : String(value); const hardened = /^[\s\u0000-\u001f]*[=+\-@]/.test(textValue) ? `'${textValue}` : textValue; return `"${hardened.replace(/"/g, '""')}"`; }
export function sortReviewRows(rows: readonly ReviewRow[]): ReviewRow[] { return rows.map((row, index) => ({ row, index })).sort((a, b) => rowCompare(a.row, b.row) || a.index - b.index).map((entry) => entry.row); }
export function buildReviewCsv(rows: readonly ReviewRow[]): string { const lines = [REVIEW_CSV_COLUMNS.map(csvCell).join(',')]; for (const row of sortReviewRows(rows)) lines.push([row.documentVersion, row.manifestSha256, row.cohortId, row.questionId, row.userId, row.draftText, row.submittedText, row.currentRevision, row.submittedRevision, row.submittedAt, row.updatedAt, row.status].map(csvCell).join(',')); return `\ufeff${lines.join('\r\n')}\r\n`; }
