import { describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import AdminReviewsClient from '../AdminReviewsClient';

const row = { documentVersion: 'v1', manifestSha256: 'a'.repeat(64), cohortId: 'c1', questionId: 'q1', userId: 'u1', draftText: 'draft', submittedText: 'answer', currentRevision: 2, submittedRevision: 1, submittedAt: '2026-09-17T00:00:00.000Z', updatedAt: '2026-09-17T00:00:01.000Z', status: 'changed-since-submit' as const };
const serverState = vi.hoisted(() => ({ access: { allowed: true, user: { id: 'u1' }, role: 'admin' } as any, rows: [] as unknown[], error: null as unknown }));
vi.mock('next/link', () => ({ default: ({ href, children }: { href: string; children: React.ReactNode }) => <a href={href}>{children}</a> }));
vi.mock('next/navigation', () => ({ redirect: vi.fn((path: string) => { throw new Error(`REDIRECT:${path}`); }) }));
vi.mock('next/headers', () => ({ cookies: vi.fn(async () => ({ get: vi.fn() })) }));
vi.mock('@supabase/ssr', () => ({ createServerClient: vi.fn(() => { const query: any = { select: vi.fn(function (this: any) { return this; }), eq: vi.fn(function (this: any) { return this; }), then: vi.fn((resolve: (result: unknown) => unknown) => resolve({ data: serverState.rows, error: serverState.error })) }; return { from: vi.fn(() => query) }; }) }));
vi.mock('@/lib/matrix-options/paper-admin-guard', async (importOriginal) => { const actual = await importOriginal<typeof import('@/lib/matrix-options/paper-admin-guard')>(); return { ...actual, getPaperAdminAccess: vi.fn(async () => serverState.access), getTrustedPaperReviewIdentity: vi.fn(async () => ({ documentVersion: 'v1', manifestSha256: 'a'.repeat(64), releaseIdentity: 'r', cohortIds: new Set(['c1']), questionIds: new Set(['q1']), cohortQuestionIds: new Map([['c1', new Set(['q1'])]]) })) }; });
import MatrixOptionsPaperReviewsPage from '../page';

describe('admin review page rendering', () => {
  it('visibly preserves document, manifest, cohort, question, reviewer, both texts, both revisions, status, and timestamps', () => { render(<AdminReviewsClient rows={[row]} state={{ kind: 'ready' }} initialFilters={{}} />); for (const value of ['v1', row.manifestSha256, 'c1', 'q1', 'u1', 'draft', 'answer', '2', '1', 'changed-since-submit', row.updatedAt, row.submittedAt]) expect(screen.getByText(value)).toBeTruthy(); });
  it('distinguishes empty, query-error, and integrity-error states', () => { const { rerender } = render(<AdminReviewsClient rows={[]} state={{ kind: 'empty' }} initialFilters={{}} />); expect(screen.getByText(/no reviews match/i)).toBeTruthy(); rerender(<AdminReviewsClient rows={[]} state={{ kind: 'query-error' }} initialFilters={{}} />); expect(screen.getByRole('alert')).toHaveTextContent(/query failed/i); rerender(<AdminReviewsClient rows={[]} state={{ kind: 'integrity-error' }} initialFilters={{}} />); expect(screen.getByRole('alert')).toHaveTextContent(/integrity validation failed/i); });
  it('renders all filters and uses the real incompatible-filter validator', async () => { render(<AdminReviewsClient rows={[]} state={{ kind: 'empty' }} initialFilters={{}} />); for (const name of ['documentVersion', 'manifestSha256', 'cohortId', 'questionId', 'userId', 'status']) expect(screen.getByLabelText(name.replace(/([A-Z])/g, ' $1').replace(/^./, (str) => str.toUpperCase()))).toBeTruthy(); serverState.access = { allowed: true, user: { id: 'u1' }, role: 'admin' }; const element = await MatrixOptionsPaperReviewsPage({ searchParams: Promise.resolve({ manifestSha256: 'b'.repeat(64) }) }); render(element); expect(screen.getByRole('alert')).toHaveTextContent(/integrity validation failed/i); });
  it('exercises forbidden auth and query failure', async () => { serverState.access = { allowed: false, status: 403, reason: 'forbidden' }; await expect(MatrixOptionsPaperReviewsPage({ searchParams: Promise.resolve({}) })).rejects.toThrow('REDIRECT:/dashboard'); serverState.access = { allowed: true, user: { id: 'u1' }, role: 'admin' }; serverState.error = new Error('database'); const element = await MatrixOptionsPaperReviewsPage({ searchParams: Promise.resolve({}) }); render(element); expect(screen.getByRole('alert')).toHaveTextContent(/query failed/i); serverState.error = null; });
});

