-- =============================================================================
-- catalog_sources: HITL-added catalog source records
-- =============================================================================
--
-- Purpose: persists HITL-added source records (citations, regulatory authorities,
-- Zotero linkages) used by the Evidence Library + Stream D Catalog Extraction
-- Agent. Referenced by `catalog_evidence_items.source_id` (TEXT slug) and by
-- the `source_ids TEXT[]` column on `promoted_parameter_values`. The latter
-- cross-references are convention-only (no DB-level FK) to match the existing
-- `promoted_parameter_values.source_ids` pattern; this is intentional.
--
-- Schema source-of-truth: `src/lib/matrix-options/provenance/source-sync.ts`
-- (CatalogSourceRow interface + submitSource payload). Column types and
-- defaults mirror what the TS code already inserts.
--
-- Author:   Stream D autonomous session (Opus 4.7), 2026-05-28.
-- Branch:   feat/stream-d-catalog-agent-scaffold.
-- Reason:   Stream D Sub-task 2 exploratory SQL confirmed this table does NOT
--           exist in Supabase, even though src/lib/matrix-options/provenance/
--           source-sync.ts has been targeting it. Calls silently no-op via
--           the safe-fallback pattern; the Evidence Library's "Add Source"
--           feature is effectively dead until this migration applies.
--
-- HITL gate: owner pastes this migration into Supabase Studio SQL Editor.
--            Does NOT depend on the Stream D staging table (20260527000004) or
--            RPC (20260527000005). Apply order is flexible relative to those.
--
-- RLS: matches the existing two-policy pattern on `parameter_value_reviews`
-- and `promoted_parameter_values`:
--   - admin / matrix_admin: manage (FOR ALL)
--   - authenticated:        read (FOR SELECT)
-- This is a catalog-grade surface (curated source records), so the broader
-- authenticated-read is appropriate; if owner wants admin-only read for
-- this surface (similar to Stream D's catalog_extraction_staging staging
-- queue), drop the authenticated-read policy below before applying.
--
-- Pre-flight exploratory SQL (run BEFORE applying):
--
--   SELECT to_regclass('public.catalog_sources') AS exists_already;
--   -- Expected: NULL.
--
--   SELECT COUNT(*) FROM public.user_roles WHERE role IN ('admin', 'matrix_admin');
--   -- Expected: >= 1 (the admin RLS gate needs at least one admin user).
--
-- =============================================================================

CREATE TABLE public.catalog_sources (
  -- Surrogate primary key.
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Stable slug identifier (e.g., 'src-hitl-acfn-wqciu-1716822000000'). Unique;
  -- the application generates this from short_citation + timestamp, or accepts
  -- a manually-slugified value. Used as the cross-table reference key by
  -- `catalog_evidence_items.source_id` (convention; no DB FK to match the
  -- existing `promoted_parameter_values.source_ids` pattern).
  source_id TEXT UNIQUE NOT NULL,

  -- Bibliographic core
  short_citation TEXT NOT NULL,
  title          TEXT NOT NULL,
  year           INTEGER,
  publisher      TEXT NOT NULL DEFAULT '',
  doi            TEXT,
  url            TEXT,

  -- Zotero linkage (nullable; sources may be added without a Zotero anchor).
  zotero_key         TEXT,
  zotero_item_type   TEXT,
  zotero_parent_key  TEXT,

  -- Authority + curation metadata. TS code passes specific enum values
  -- (see SubmitSourceRequest comments in source-sync.ts) but the existing
  -- catalog tables use TEXT without CHECK enforcement; matching that pattern
  -- here for consistency. Application layer remains authoritative on values.
  authority_scope         TEXT NOT NULL DEFAULT '',
  authority_tier          TEXT NOT NULL DEFAULT '',
  currentness_status      TEXT NOT NULL DEFAULT 'unknown',
  bc_protocol_alignment   TEXT NOT NULL DEFAULT 'none',
  canonical_source_status TEXT NOT NULL DEFAULT '',
  role                    TEXT NOT NULL DEFAULT '',

  -- Provenance
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.catalog_sources IS
  'HITL-added source records (citations, regulatory authorities, Zotero linkages). Referenced by source_id (TEXT slug) from catalog_evidence_items and from promoted_parameter_values.source_ids[]. Cross-references are convention-only; no DB FK on those references to match the existing array-of-strings pattern.';

COMMENT ON COLUMN public.catalog_sources.source_id IS
  'Stable slug identifier. Generated by submitSource() as src-hitl-<slug>-<timestamp> or accepted as a manually-slugified value. UNIQUE; referenced cross-table by catalog_evidence_items.source_id and promoted_parameter_values.source_ids[].';

COMMENT ON COLUMN public.catalog_sources.authority_scope IS
  'Geographic / jurisdictional scope: BC | Canada_federal | US_federal | general. Application layer enforces values.';

COMMENT ON COLUMN public.catalog_sources.authority_tier IS
  'Authority weighting tier: tier_1_government_or_regulatory | tier_2_peer_reviewed_literature | tier_3_supporting_science | implementation_scaffold.';

COMMENT ON COLUMN public.catalog_sources.canonical_source_status IS
  'Canonical-source state: direct_source_verified | needs_direct_source_check | needs_exact_source_locator | not_applicable.';

COMMENT ON COLUMN public.catalog_sources.role IS
  'Source role: canonical_candidate | reference_mining | policy_compilation | implementation_scaffold.';

-- Indexes
-- Query path: Zotero lookups during agent runs ("do we already have a source
-- for this Zotero key?"). Standalone since fetchHitlSources sorts by created_at
-- but doesn't filter on zotero_key today.
CREATE INDEX catalog_sources_zotero_key_idx
  ON public.catalog_sources (zotero_key)
  WHERE zotero_key IS NOT NULL;
COMMENT ON INDEX public.catalog_sources_zotero_key_idx IS
  'Supports Zotero-key dedup lookups during Catalog Extraction Agent runs and during HITL Add Source form submissions. Partial: zotero_key is NULL for sources added without a Zotero anchor.';

-- Row-level security
ALTER TABLE public.catalog_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage catalog sources"
  ON public.catalog_sources
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles
       WHERE user_id = auth.uid()
         AND role IN ('admin', 'matrix_admin')
    )
  );

CREATE POLICY "Authenticated users can read catalog sources"
  ON public.catalog_sources
  FOR SELECT
  USING (auth.role() = 'authenticated');

REVOKE ALL ON public.catalog_sources FROM anon;
